### PR TITLE
Make top-left logo link back to home

### PR DESCRIPTION
**Pull request by webthethird**
Re: [this issue](https://github.com/SergeKireev/upgradehub-issues/issues/1) I opened

Should be as simple as wrapping the image and text in an anchor tag, right?  

I'm not the most familiar with React, but I know HTML

### CODE REVIEW

**Comment by eliteWalrus4164** [comment]
Yes that should be good! 
Please use the relative path '/' instead of 'https://upgradehub.xyz' as it would break local dev env (served at localhost:3001) and we're good for merging 🙏

**Comment by webthethird** [comment]
@SergeKireev Done!

**Comment by eliteWalrus4164** [comment]
Unfortunately after testing it breaks the text of the logo as shown below:
image

I think we should put the  <Row> tag inside the anchor to preserve layout. Did you manage to setup the dev env as per the readme.md? Happy to help if needed

**Comment by webthethird** [comment]
My bad, I was being lazy and just editing the code on Github, since it
seemed like it should be so simple!

I will probably set up the dev environment and do it properly later today
or tomorrow. I doubt I'll have any issues, but if I do I'll ping you.

**Comment by webthethird** [comment]
Looks good now in my localhost :rocket:

**Comment by eliteWalrus4164** [comment]
Aand it's live :)

**Pull request merged**
